### ISSUE TITLE
password field in the Heroku Config should be hidden

### ISSUE THREAD

**Issue by anilkumarbp** [grokify/glipbot-getsatisfaction#1]
password field in the Heroku Config should be hidden:

https://github.com/grokify/glipbot-getsatisfaction#running-getsat-glipbot-on-heroku

**Comment by grokify** [comment]
Good point and worth investigating. Upon research, this may not be possible since it's not mentioned in Heroku pages for `app.json` or the 'Deploy to Heroku' button:
- https://devcenter.heroku.com/articles/app-json-schema
- https://devcenter.heroku.com/articles/heroku-button

I've asked the following question on Stack Overflow and will leave this open to see if there's additional info:
- http://stackoverflow.com/questions/39908569/how-to-hide-config-value-in-deploy-to-heroku-form-via-app-json

**Comment by grokify** [comment]
@anilkumarbp It seems Heroku doesn't support this so I'm closing this now.

If you know how to do this, please post how here and reopen.
